### ISSUE TITLE
Investigate/Plan out STD OUT module

### ISSUE THREAD

**Issue by TaylorJesse** [promethean-jpl/promethean.ai#28]
- [x] Research Command Line Interfaces
- [x] Create AccessPoint class
- [x] allow access point class to receive arguments from the command line
- [x] Investigate Apache Common CLI
- [x] Investigate Jcommander
- [x] Add API interface to initiate Parser
- [x] Add API interface to throw errors upon receiving errors
- [x] getters and setters for command/input
- [x] Make "run" command call graph generator (if approved by team
- [x] refactor API to have different functions for different functionality

**Comment by samdreed21** [comment]
Tentative TODO:
- Ask about what's needed for STDOUT
- Feed input files
- Have it respond to messages sent from within the system

**Comment by samdreed21** [comment]
Common CLI provides a very simple interface for parsing arguments passed through command line.

**Comment by samdreed21** [comment]
JCommander allows for clean implementation of argument handling (handling is abstracted to another class) and flexible file upload. Requires xml implementation for defining requirements.
